default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db_sync
  host: db #localhost
  port: 5432 #5430
  username: postgres
  password: mysecretpassword

test:
  <<: *default
  database: db_sync_test
  host: db
  port: 5432
  username: postgres
  password: mysecretpassword

production:
  <<: *default
  database: your_database_name_production
  host: db
  port: 5432
  username: postgres
  password: mysecretpassword
